### PR TITLE
Do not update ttl on reads for absolute expirations

### LINKED ISSUE #15: Make ReplaceItem call optional
Regarding this line:

https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L104

```cs
try
{
    await this.cosmosContainer.ReplaceItemAsync(
            partitionKey: new PartitionKey(key),
            id: key,
            item: cosmosCacheSessionResponse.Resource,
            requestOptions: new ItemRequestOptions()
            {
                IfMatchEtag = cosmosCacheSessionResponse.ETag,
            },
            cancellationToken: token).ConfigureAwait(false);
}
catch (CosmosException cosmosException) when (cosmosException.StatusCode == HttpStatusCode.PreconditionFailed)
{
    // Race condition on replace, we need to get the latest version of the item
    return await this.GetAsync(key, token).ConfigureAwait(false);
}
```

I assume the reason for this is to reset the ttl on every read access. This may make sense for session state but maybe not non-session related caching, such as application data you want cached for one minute or one hour regardless of reads when using the IDistributedCache directly and not through the HTTP session.

Suggested enhancement:
```cs
cosmosCacheOptions.ResetTimeToLiveOnRead = false;
```

This also comes with a big performance hit of sending the cached data back to the server on every access for no reason other than to reset the ttl which would more than double the overall operation time as writes/indexing are slower than reads, correct me if I'm wrong. It's a shame Cosmos doesn't offer a specific ttl reset operation or even better to reset the ttl on a read with an optional parameter.

Am I wrong in the above?

Also, would love this as a Nuget package as well!

### PR DESCRIPTION
**Pull request by krispenner**
Only update cached item ttl on reads if sliding expiration was explicitly set in cache entry options.

Closes #15

### CODE REVIEW

File: src/CosmosCache.cs [hunk 1]
```diff
@@ -215,6 +258,7 @@ private static CosmosCacheSession BuildCosmosCacheSession(string key, byte[] con
                 SessionKey = key,
                 Content = content,
                 TimeToLive = timeToLive,
+                IsSlidingExpiration = timeToLive.HasValue ? options.SlidingExpiration.HasValue : (bool?)null,
```
Comment (ealsur) [inline src/CosmosCache.cs]: Why not:
```suggestion
                IsSlidingExpiration = timeToLive.HasValue && options.SlidingExpiration.HasValue,
```

**Review by ealsur — CHANGES_REQUESTED** [review]
Please add an entry on the `changelog.md` file in the Unreleased section, under the last item of the list, which points to your PR (like the one that is already there)

File: src/CosmosCache.cs (hunk 1 above)
Comment (krispenner) [reply src/CosmosCache.cs]: No real reason other then to have `IsSlidingExpiration` set to null if `TimeToLive` was null so they would sort of be in sync with each other. But logically it isn't required to be null. If we use your suggestion then we could also change `IsSlidingExpiration` to be `bool` instead of `bool?`. Would you also prefer that too?

Comment (ealsur) [reply src/CosmosCache.cs]: Honestly the only thing that threw me off was the `(bool?)null`, it made understanding a tad bit difficult. I don't mind the `bool?` type.

**Review by ealsur — APPROVED** [review]

**Comment by ealsur** [comment]
I'll merge upon resolution of the open comment.

File: src/CosmosCache.cs (hunk 1 above)
Comment (ealsur) [reply src/CosmosCache.cs]: Just to clarify. If the value is being set on some code path, like this one, I would either set it as `true` or `false`, setting it to `(bool?)null` is kind of an implicit `false` which is harder to understand. I'd leave the `null` possibility for a scenario where the value does not exist in the source like I mentioned in my previous comment (code migration to a version that contains the attribute).

Comment (krispenner) [reply src/CosmosCache.cs]: ok sounds good

**Comment by ealsur** [comment]
Thanks @krispenner !
